### ISSUE TITLE
Error after launching on Windows

### ISSUE THREAD

**Issue by GeorgeHahn** [dvcrn/markright#17]
After launching either the 32 or 64 bit build on Windows 10 (build 10565), I'm shown the following error message. (Nothing else is shown.)

![2015-11-09 22_56_14-start](https://cloud.githubusercontent.com/assets/502747/11054084/2b0b7c7c-8735-11e5-9669-e017d18c78fd.png)

Anything I can do to debug the issue?

After some further investigation, release 0.1.1 launches, but opens to a blank window.

**Comment by dvcrn** [comment]
Looks like a bug.

`buildFromTemplate` is a electron api call. I think this could be related to this line https://github.com/dvcrn/markright/blob/master/src/cljs/markright/main.cljs#L182-L183. `(when)` returns nil here which doesn't have the 'position' element. 

I'll fix that and push a new version right away.

**Comment by wildart** [comment]
The same error on Linux x64 build.

**Comment by dvcrn** [comment]
I re-built with a fix though don't have a windows / linux machine with me to test. Could you give the following builds a try? https://github.com/dvcrn/markright/releases/tag/0.1.4

**Comment by GeorgeHahn** [comment]
Windows 64 bit works!
