### ISSUE TITLE
TCP connection error

### ISSUE THREAD

**Issue by GeorgeHahn** [dvcrn/markright#18]
Two errors are shown if the application cannot connect to the internet upon launching (they do not hamper functionality after they've been closed)

![2015-11-09 23_27_59-photos](https://cloud.githubusercontent.com/assets/502747/11054392/9cbbca62-8739-11e5-8d51-fb2ad30ffceb.png)
![2015-11-09 23_28_16-photos](https://cloud.githubusercontent.com/assets/502747/11054393/9cbc0e6e-8739-11e5-912a-c58cb8ef9b66.png)

**Comment by dvcrn** [comment]
Could be https://github.com/dvcrn/markright/blob/master/src/cljs/markright/main.cljs#L226-L241

**Comment by GeorgeHahn** [comment]
Yup, looks about right. After allowing it through my firewall, the error is replaced with an update notification :octopus:

**Comment by dvcrn** [comment]
Fixed in 0.1.5
