### ISSUE TITLE
Task list checkboxes aren't rendered

### ISSUE THREAD

**Issue by tedajax** [dvcrn/markright#23]
GFM supports task lists using the syntax:

```md
- [ ] a
- [x] b
- [x] c
```

which gets rendered as pretty checkboxes:

- [x] a
- [ ] b
- [ ] c

Currently markright does not seem to support this.  Not sure if it's planned to be supported or not because it's obviously a little more in depth than the typical markdown rendering (should clicking checkboxes in the render view update the file contents?) but I figured I should open an issue just to document whether or not that's the case.

**Comment by dvcrn** [comment]
Markright currently uses [marked](https://github.com/chjj/marked) for gfm markdown rendering. There is a PR open for this feature but it is not merged back in yet https://github.com/chjj/marked/pull/587

We might need to go with a fork for the time being or find a different (better?) markdown renderer

**Comment by dvcrn** [comment]
![screen shot 2015-11-11 at 2 39 31 pm](https://cloud.githubusercontent.com/assets/688326/11084722/0e9fe3ae-8882-11e5-9381-074905eae76c.png)

**Comment by GeorgeHahn** [comment]
:heart_eyes:

**Comment by tedajax** [comment]
Glorious :+1:
