### ISSUE TITLE
Markright not working with window management software in OSX.

### ISSUE THREAD

**Issue by tedajax** [dvcrn/markright#25]
Needs more investigation into how my particular window management software (SizeUp) actually works but commands to switch monitors, switch spaces, resize, and move the markright window fail to actually do anything.  SizeUp shows it's display indicating that it's doing it's part correctly but markright doesn't appear to be responding to the events.

**Comment by dvcrn** [comment]
I am using Hyperdock myself and all commands for resizing, moving or pushing the window around work fine on MarkRight. Is it just ignoring it or does it react in a wrong way?

**Comment by tedajax** [comment]
My apologies, some combination of currently running apps mixed with days of up time caused my window manager to freak out and only work on *some* windows.  Should have just tried restarting my window manager before opening an issue :-1:

Sorry!

**Comment by dvcrn** [comment]
Great to hear! Thanks for the feedback
