### ISSUE TITLE
Local images aren't loading

### ISSUE THREAD

**Issue by seriema** [dvcrn/markright#28]
I created this markdown file using Atom (with [MarkdownPreview](https://atom.io/packages/markdown-preview)) and it looked fine there. It also renders fine [GitHub](https://github.com/kodcentrumcollaborative/Aktuella-uppgifter-i-Scratch/tree/master/block1_bugrace_intro#kom-igång-med-scratch). But `markright` seems to have issues loading the images. The demo markdown that `markright` starts with is using an online image, so I'm guessing the issue is with local images.

![image](https://cloud.githubusercontent.com/assets/693684/11088687/7366e512-8864-11e5-944c-eaf727121e3d.png)

![image](https://cloud.githubusercontent.com/assets/693684/11088720/a5de5cd2-8864-11e5-89bc-78fd69c8fa31.png)

**Comment by dvcrn** [comment]
Released with 0.1.7
