### ISSUE TITLE
README gets in the way of working with MarkRight

### ISSUE THREAD

**Issue by RWeigelt** [dvcrn/markright#29]
Showing the README on first start is a nice touch, but opening/working with files in MarkRight 0.1.6 is a pain right now.

* I cannot start MarkRight with a clean editing window, the README is always there
* Opening a file will open a dialog box telling me that changes will be lost
* Passing a file name as a command line parameter to markright.exe doesn't seem to work.

(Tested on Windows 10)

BTW: Nice editor!

**Comment by dvcrn** [comment]
Agreed. I left it in there as a kind of demo but noticed that as well. Plus I think removing the default text will close https://github.com/dvcrn/markright/issues/14 as well
