### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by dvcrn** [dvcrn/markright#3]
The current release process is already building for linux, I just don't know what to do with this folder or how to package it. 

![screen shot 2015-11-04 at 12 12 56 pm](https://cloud.githubusercontent.com/assets/688326/10928600/6b447b6e-82ed-11e5-8d2c-889c3ca285df.png)

**Comment by cuonic** [comment]
As long as the executable is in the root directory of the tarball then most people are happy, I sure am, it works great :)

**Comment by aogilvie** [comment]
@dvcrn `brew cask` is not available with linuxbrew, any other methods for install? Does cask _have_ to be used?

**Comment by dvcrn** [comment]
@aogilvie you can grab the latest zipped build here https://github.com/dvcrn/markright/releases. I don't have a linux machine with me but please feel free to contribute a linuxbrew formula if you think it makes sense.

**Comment by dvcrn** [comment]
Since some people confirmed that the builds are working on linux, I am removing the `(untested)` flag.
