### ISSUE TITLE
Scrollbar issue

### ISSUE THREAD

**Issue by ggoss** [dvcrn/markright#33]
On the most recent linux x64 binary, I still had the scrollbar issue mentioned in [#21](https://github.com/dvcrn/markright/issues/21). I'm not sure how to properly contribute the fix (never done it before, and don't want to step on any toes), but here's how I fixed it.

I made two changes to `main.css`:
- under line 43, `#parsed markdown {`, I added `width: 50%;`
- under line 51, `.markdown-body {`, I added `width: 100%;`
  
For the record, everything else I tested in the build seems to work well. Great job!

**Comment by dvcrn** [comment]
Interesting, thank you! I'll try to verify these changes asap.
