### ISSUE TITLE
Can't save new file

### ISSUE THREAD

**Issue by Wideshanks** [dvcrn/markright#35]
Opening an already existing file allows me to `File > Save` just fine, but try to `File > Save as` a new file and it throws an error.

![image](https://cloud.githubusercontent.com/assets/2061925/11279605/8d0164dc-8ebf-11e5-92d8-d74eb9499927.png)

Whatever `filename` is provided, the error message makes it look like it's trying to save to a glob: `filename.*`.

Unsure how to check the version number, but I believe this is 0.1.8 I'm using. Windows 8.

**Comment by dvcrn** [comment]
Hmm. I tried to reproduce this on my Mac but don't run into this error. 

1. Open MarkRight
2. Type random stuff in 
3. Save
4. File dialog pops up, after picking a file, saving works fine
5. Close MarkRight (or keep it open)
6. Open same file again
7. Change text so that the * indicator appears at the top of the page
8. Hit 'save as'
9. File saves accordingly (and updates path in title)

**Comment by djungowski** [comment]
@dvcrn That is because this error only appears in Windows. I can confirm that this error happens on Win7 32Bit aswell as Win10 64 Bit

**Comment by urmilparikh** [comment]
+1

I too face this issue in Windows.
Possible cause could be that `Save as type` is `All Files (*.*)`, which may add `.*` at the end of file name.

**Comment by gauravmahto** [comment]
+1
I too face this issue.
On Win10_x64

**Comment by dvcrn** [comment]
can someone try one of these versions? 

https://dl.dropboxusercontent.com/u/27953127/tmp/MarkRight_Windows32.exe
https://dl.dropboxusercontent.com/u/27953127/tmp/MarkRight_Windows64.exe

It would help a lot since I don't have a windows machine to confirm

**Comment by djungowski** [comment]
Works with the 32Bit Version

**Comment by urmilparikh** [comment]
Works with 64-bit version as well.

However, it still shows 'Electron' in Open-with menu and still does not open the file when double-clicked a file in Windows Explorer. May be, command-line arguments are ignore at some stage.

**Comment by dvcrn** [comment]
Thanks for the feedback guys! Then I can finally get rid of this annoying bug 😊

**Comment by djungowski** [comment]
Btw. You might consider using one of the VMs provided at https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/windows/ to test things on Windows

**Comment by dvcrn** [comment]
https://github.com/dvcrn/markright/releases/tag/0.1.11
