### ISSUE TITLE
Question: How to connect to the CLJS Repl

### ISSUE THREAD

**Issue by aminmeyghani** [dvcrn/markright#38]
Was wondering how I can connect to the CLJS Repl in development. Thanks.

**Comment by dvcrn** [comment]
Hi,

there are build commands available for compiling markright, one for the backend, one for the frontend.
The backend task (`main-dev`) does not have a interactive REPL yet. The frontend task (`ui-dev`) is a full REPL. @thheller just didn't add prompt input or similar indicators to shadow-build yet. 

Once a browser is connected you should be able to dump clojurescript code into it.

**Comment by aminmeyghani** [comment]
awesome, thanks !
