### ISSUE TITLE
ENOENT

### ISSUE THREAD

**Issue by CosticaPuntaru** [dvcrn/markright#42]
on windows, if you want to create a file from scratch, and you don't open an existing one, when you want to save your md it throws the fallowing error
![capture](https://cloud.githubusercontent.com/assets/6418405/15042819/fc2a20e4-12cf-11e6-9399-b37a16077de9.JPG)

**Comment by dvcrn** [comment]
Seems to be the same as https://github.com/dvcrn/markright/issues/35

**Comment by dvcrn** [comment]
@CosticaPuntaru can you try the following versions? 

https://dl.dropboxusercontent.com/u/27953127/tmp/MarkRight_Windows32.exe
https://dl.dropboxusercontent.com/u/27953127/tmp/MarkRight_Windows64.exe

It would help a lot since I don't have a windows machine to confirm

**Comment by CosticaPuntaru** [comment]
look like the links you shared worked for me

**Comment by dvcrn** [comment]
https://github.com/dvcrn/markright/releases/tag/0.1.11
